_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": r1_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": cond_S1_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": regularization_loss_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": cond_S2_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": regularization_loss_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": loss_plot.size
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": loss_plot.width
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": r1_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": cond_S1_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": loss_plot.path
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": loss_plot.height
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": loss_plot._type
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": Ratio 1
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": Ratio 2
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": cond_S2_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": loss_plot.format
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": loss_plot.sha256
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": IG
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": r2_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": reconstruction_loss_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": r2_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": reconstruction_loss_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "3":
                - 7
                - 55
                - 66
            "4": 3.10.18
            "5": 0.20.1
            "8":
                - 2
            "12": 0.20.1
            "13": linux-x86_64
feat_size:
    value: 79
feature_extractor_type:
    value: linear
hidden_size:
    value: 79
lambda_kappa:
    value: 1
lambda_r1:
    value: 100
lambda_r2:
    value: "1e7"
lambda_reg:
    value: 1
lr:
    value: "5e-3"
task:
    value: regression
