_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "3":
                - 13
                - 16
                - 55
            "4": 3.10.18
            "5": 0.20.1
            "8":
                - 2
            "12": 0.20.1
            "13": linux-x86_64
data:
    value:
        batch_size: 64
        dataset_name: mnist
        max_samples_per_class: null
feat_size:
    value: 784
feature_extractor_type:
    value: linear
hidden_size:
    value: 784
lambda_r1:
    value: 1
lambda_r2:
    value: "5e7"
lambda_reg:
    value: "1e-7"
lr:
    value: "1e-3"
model:
    value:
        feat_size: 784
        feature_extractor_type: linear
        hidden_size: 784
        lambda_r1: 1
        lambda_r2: "5e7"
        lambda_reg: "1e-7"
        lr: "1e-3"
        task: classification
task:
    value: classification
training:
    value:
        callbacks:
            checkpoint:
                mode: min
                monitor: train_loss
                save_top_k: 1
            early_stopping:
                mode: min
                monitor: train_loss
                patience: 3
        gpus: 1
        log_every_n_steps: 1
        logger:
            project_name: immu_cond_num
        max_epochs: 1
        precision: 32
