_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "3":
                - 13
                - 16
                - 55
            "4": 3.10.18
            "5": 0.20.1
            "8":
                - 2
            "12": 0.20.1
            "13": linux-x86_64
data:
    value:
        batch_size: 64
        d1_path: data/imagenet
        d2_name: country211
        d2_path: data/country211
        dataset_name: imagenet
model:
    value:
        feat_size: 512
        feature_extractor_type: pt_imagenet
        lambda_kappa: 1
        lambda_r1: "1e-4"
        lambda_r2: "2e6"
        lr: "1e-5"
        task: classification
training:
    value:
        callbacks:
            checkpoint:
                mode: min
                monitor: train_loss
                save_top_k: 1
            early_stopping:
                mode: min
                monitor: train_loss
                patience: 3
        gpus: 1
        log_every_n_steps: 1
        logger:
            project_name: immu_cond_num
        max_epochs: 3
        precision: 32
