_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "3":
                - 7
                - 55
                - 66
            "4": 3.10.18
            "5": 0.20.1
            "8":
                - 2
            "12": 0.20.1
            "13": linux-x86_64
