_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "3":
                - 13
                - 16
                - 55
            "4": 3.10.18
            "5": 0.20.1
            "8":
                - 2
            "12": 0.20.1
            "13": linux-x86_64
data:
    value:
        batch_size: 64
        d1_path: data/house_price/D1.csv
        d2_path: data/house_price/D2.csv
        dataset_name: tabular
feat_size:
    value: 79
feature_extractor_type:
    value: linear
hidden_size:
    value: 79
lambda_kappa:
    value: 1
lambda_r1:
    value: 100
lambda_r2:
    value: "1e7"
lambda_reg:
    value: 1
lr:
    value: "5e-3"
model:
    value:
        feat_size: 79
        feature_extractor_type: linear
        hidden_size: 79
        lambda_kappa: 1
        lambda_r1: 100
        lambda_r2: "1e7"
        lambda_reg: 1
        lr: "5e-3"
        task: regression
task:
    value: regression
training:
    value:
        callbacks:
            checkpoint:
                mode: min
                monitor: train_loss
                save_top_k: 1
            early_stopping:
                mode: min
                monitor: train_loss
                patience: 3
        gpus: 2
        log_every_n_steps: 1
        logger:
            project_name: immu_cond_num
        max_epochs: 10
        precision: 32
